# Generated by Django 5.2.8 on 2025-12-02 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Animal')),
                ('especie', models.CharField(max_length=50, verbose_name='Espécie')),
                ('genero', models.CharField(max_length=50, verbose_name='Gênero')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='animais/')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Evento')),
                ('instituicao', models.CharField(max_length=200, verbose_name='Instituição')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora do Evento')),
                ('local', models.CharField(max_length=200, verbose_name='Local do Evento')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('site_instituicao', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do site')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Instituição')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('data_nasc', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='animais/', verbose_name='Foto de Perfil')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animal', verbose_name='Animal')),
                ('participante_adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_como_adotante', to='app.pessoa')),
                ('participante_doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_como_doador', to='app.pessoa')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='app.conversa')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['data_envio'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='doador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Doador'),
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adocao', models.DateField(auto_now_add=True, verbose_name='Data de Adoção')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animal', verbose_name='Animal')),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adotante', to='app.pessoa', verbose_name='Adotante')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Doador')),
            ],
            options={
                'verbose_name': 'Adoção',
                'verbose_name_plural': 'Adoções',
            },
        ),
    ]
