# Generated by Django 5.2.8 on 2025-12-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='site_instituicao',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
