# Generated by Django 5.2.7 on 2025-10-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_pessoa_idade_pessoa_data_nasc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='animais/'),
        ),
    ]
