# Generated by Django 5.2.8 on 2025-12-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_evento_site_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='animais/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='site_instituicao',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do site'),
        ),
    ]
