# Generated by Django 5.2.7 on 2025-10-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_animal_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
