# Generated by Django 5.2.7 on 2025-10-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_animal_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(max_length=128, verbose_name='Senha'),
        ),
    ]
