# Generated by Django 5.2.7 on 2025-11-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pessoa_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='instituicao',
            field=models.CharField(max_length=200, verbose_name='Instituição'),
        ),
    ]
