# Generated by Django 5.2.8 on 2025-11-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_conversa_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='fotoperfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil'),
        ),
    ]
