# Generated by Django 5.2.8 on 2025-11-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_pessoa_fotoperfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='fotoperfil',
            new_name='foto_perfil',
        ),
    ]
