# Generated by Django 5.2.8 on 2025-11-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_fotoperfil_pessoa_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descricao',
        ),
    ]
